// src/App.vue
<!-- src/App.vue -->
<template>
  <div v-if="loadingSession" class="min-h-screen bg-gray-900 flex items-center justify-center text-white">
    <p>Loading...</p>
  </div>
  
  <Game v-else-if="session" :session="session" />
  
  <Auth v-else />
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { supabase } from './supabase'
import Auth from './components/Auth.vue'
import Game from './components/Game.vue'

const session = ref(null)
const loadingSession = ref(true)

onMounted(() => {
  // ดึง Session ปัจจุบันเมื่อโหลดหน้าเว็บ (เพื่อไม่ให้หลุดตอนรีเฟรช)
  supabase.auth.getSession().then(({ data }) => {
    session.value = data.session
    loadingSession.value = false
  })

  // ดักจับเหตุการณ์เวลา Login, Logout หรือ Token หมดอายุ
  supabase.auth.onAuthStateChange((_event, _session) => {
    session.value = _session
  })
})
</script>

// app/page.tsx
'use client'

import { useEffect, useState } from 'react'
import { supabase } from '@/lib/supabase'
import Auth from '@/components/Auth'
import Game from '@/components/Game'
import type { Session } from '@supabase/supabase-js'

export default function Home() {
  const [session, setSession] = useState<Session | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    supabase.auth.getSession().then(({ data }) => {
      setSession(data.session)
      setLoading(false)
    })

    const { data: authListener } = supabase.auth.onAuthStateChange(
      (_event, _session) => {
        setSession(_session)
      }
    )

    return () => {
      authListener.subscription.unsubscribe()
    }
  }, [])

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-900 flex items-center justify-center text-white">
        <p>Loading...</p>
      </div>
    )
  }

  return session ? <Game session={session} /> : <Auth />
}
